name: publish @devmalik/classnames
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn test
      - run: npm publish --access public --tag $GITHUB_REF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
